name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.4
      - name: Install dependencies
        run: go mod tidy
      - name: Making sure dependecies were installed
        run: go get
      - name: Check Go version
        run: go version
      - name: List Go dependencies
        run: go list -m all
      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.54.2
          sudo mv ./golangci-lint /usr/local/bin/
      - name: Run golangci-lint
        run: golangci-lint run
